# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
pod 'Alamofire', '~>  5.7.1' # For Api call
pod 'SkeletonView'
pod 'SwiftMessages'
pod 'SSSpinnerButton' 
pod 'IQKeyboardManagerSwift'
  target 'demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoUITests' do
    # Pods for testing
  end

end
